### ISSUE TITLE
Scale is based on the top of the map instead of the center

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/azure-maps-scale-bar-control#1]
When we implemented our own distance measuring tool I noticed that the scale bar was off. It seemed to be correct on the top of the map, instead of at the centre like expected. I think there is an error in the `_updateScaleBar `method. The documentation of `camera.center `says it returns positions, but it is used as pixels here. 

https://github.com/Azure-Samples/azure-maps-scale-bar-control/blob/4ef498870f3c26cfcb05d58ba42738d2453e28fa/dist/azure-maps-scale-bar-control.js#L106

changing this line to use  `positionsToPixels()` instead of `pixelsToPositions()` solved the issue in our project.

**Comment by rbrundritt** [comment]
Thanks for the feedback. This has been fixed in version 0.0.3.
